### ISSUE TITLE
Overlay not rendering when steps are skipped (Target not mounted)

### ISSUE THREAD

**Issue by ryanewtaylor** [gilbarbara/react-joyride#519]
## 🐛 Bug Report

Under yet to be determined specific circumstances the overlay is not rendering when steps are skipped. But here's what I know...

## To Reproduce

Browser: Chrome
React-Joyride Version: 2.0.5

I set up React-Joyride to render 3 steps like so...

```json
"steps": [
    {
      "title": "step1",
      "content": "step1",
      "placement": "right",
      "target": "div[title='step1']"
    },
    {
      "title": "step2",
      "content": "step2",
      "placement": "left",
      "target": "div[id='step2']"
    },
    {
      "title": "step3",
      "content": "step3",
      "placement": "left",
      "target": "div[class~='icon-node'][title='step3']""
    }
  ]
```

### No Missing DOM Nodes
If the divs for step1, step2, and step3 exist everything proceeds normally when I start the tour. The overlay is displayed correctly at each step.

### Missing One or More DOM Nodes 
If the div for step2 is missing when I start the tour the overlay is displayed on step1 (only on the first pass). I click next and the tour correctly skips to step3 but the overlay is not displayed. If I click back, the overlay is also missing from step1. 

If I stop and restart the tour this issue repeats itself.

I noticed that when the overlay is not displayed, the DOM has an empty `<div id="react-joyride-portal"></div>` element. 

## Expected behavior

The overlay should be displayed in all cases.

## Link to repl or repo (highly encouraged)

I have been trying to replicate this issue in a repo but I cannot, yet. Unfortunately, this seems to be specific with the application in which I am integrating React-Joyride. I am hoping for some additional tips as to where to look for potential issues.

I looked at the source and it seems like the only case where a `<div className="react-joyride__overlay" />` element should not be rendered is either when the overlay is disabled (it is not in our app) or when the lifecyle is not TOOLTIP (our tooltip shows so I think lifecycle is tooltip).

## Run `npx envinfo --system --binaries --npmPackages react-floater`

```bash
   OS: Windows 10
    CPU: (2) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 1.97 GB / 8.00 GB
  Binaries:
    Node: 10.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by gilbarbara** [comment]
Hey,

UI problems are super hard to guess, especially when you can't reproduce, as you've said.
Did you try to set the debug prop? Nothing helpful there?

**Comment by ryanewtaylor** [comment]
I did set the debug prop. Nothing stuck out to me. At least, I didn't see any warnings or errors. Should there be any debug information related to whether or not the overlay should be displayed? It didn't seem like there was from the source.

**Comment by gilbarbara** [comment]
@ryanewtaylor I don't think there are messages specific to the Overlay but it might show something else.
Is the `react-joyride__overlay` rendered at all?

**Comment by ryanewtaylor** [comment]
@gilbarbara , the `react-joyride__overlay` does not render in the failing case. The `react-joyride-portal` does render, but there are no children. Here's a sample of what I see in the failing case when `debug=true`.

![image](https://user-images.githubusercontent.com/1215819/58971209-f0fe2400-8788-11e9-835d-435ef8fdccbe.png)

**Comment by gilbarbara** [comment]
Since there's no reproduction example, I'm closing this.

**Comment by xiajinchun** [comment]
@ryanewtaylor 
Hi, I have some problem, did you have solved this problem? 
I am using React-Joyride Version: 2.2.1

**Comment by xiajinchun** [comment]
![image](https://user-images.githubusercontent.com/4453349/90500270-400d5a80-e17d-11ea-940d-a9ff1afb7b8a.png)

**Comment by ZeRodolfo** [comment]
@xiajinchun i'm have same problem, i noticed that the problem is generate when my data from redux update my component. However i didn't resolve in moment

**Comment by inf3rnus** [comment]
Problem still seems to exist, I'm experiencing this as well

**Comment by LWronka** [comment]
I have similar issue, I have implemented 5 steps, on 3rd step data are fetched ( used redux-saga and redux) and on 3rd step overlay is not showing. I saw that on faster internet connections sometimes overlay is showing but on slower always is missed.

@gilbarbara are you experienced sth like that ? Fetching data could cause overlay break ?

**Comment by gilbarbara** [comment]
@LWronka 

As I said above it's impossible to debug UI problems without an example.
But it could be related to the async loading. You might need to use the controlled mode and load the data before changing the step.

**Comment by cplayer11** [comment]
@gilbarbara 
same problem, not same reason though

example modified from react-joyride-demo: https://codesandbox.io/s/new-glade-ncw57

changes in `Basic\index.tsx`
1. add `disableBeacon: true` to each step
2. use `<div style={{ display: "none" }}>` to hide step 3 target

overlay will be disappeared after skip step 3

**Comment by trmpowell** [comment]
@gilbarbara, looks like others are still having this problem. I can also see this issue same as @cplayer11 - when a step uses `disableBeacon: true`, the overlay is not rendered. Any chance this issue can be reopened?

**Comment by gilbarbara** [comment]
@trmpowell Feel free to submit a PR

**Comment by guiquintelas** [comment]
My problem was manually managing the index and also calling the primary `onClick` and back `onClick`, removing both fixed the problem

**Comment by gilbarbara** [comment]
Fixed in 2.5.x
